In [1]:
from sklearn.datasets import fetch_20newsgroups


In [2]:
cats = ['alt.atheism', 'sci.space'] # more categories are also available like 'talk.religion.misc', 'comp.graphics'.
newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)
list(newsgroups_train.target_names)

['alt.atheism', 'sci.space']

In [3]:
newsgroups_train.filenames.shape
newsgroups_train.target.shape
newsgroups_train.target[:10]

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0])

In [5]:
newsgroups_train.target.shape

(1073,)

In [6]:
newsgroups_train.filenames.shape

(1073,)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(newsgroups_train.data)

In [13]:
vectors = vectors.toarray()

In [14]:
vectors

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.04199996, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [24]:
import numpy as np
np.unique(newsgroups_train.target)

array([0, 1])

In [29]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

In [30]:
newsgroups_test = fetch_20newsgroups(subset='test',categories=cats)
vectors_test = vectorizer.transform(newsgroups_test.data)

In [33]:
newsgroups_test.filenames.shape

(713,)

In [34]:
clf = MultinomialNB(alpha=.01)
clf.fit(vectors, newsgroups_train.target)

MultinomialNB(alpha=0.01)

In [41]:
pred = clf.predict(vectors_test)
print(metrics.classification_report(newsgroups_test.target, pred))#average='macro'

              precision    recall  f1-score   support

           0       0.99      0.97      0.98       319
           1       0.97      0.99      0.98       394

    accuracy                           0.98       713
   macro avg       0.98      0.98      0.98       713
weighted avg       0.98      0.98      0.98       713



In [42]:
from sklearn.neighbors import NearestCentroid

In [44]:
clf2 = NearestCentroid()
clf2.fit(vectors, newsgroups_train.target)

NearestCentroid()

In [45]:
pred2 = clf.predict(vectors_test)
print(metrics.classification_report(newsgroups_test.target, pred2))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98       319
           1       0.97      0.99      0.98       394

    accuracy                           0.98       713
   macro avg       0.98      0.98      0.98       713
weighted avg       0.98      0.98      0.98       713

