In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# df = pd.read_csv("spam.csv", encoding = "latin")
df = pd.read_csv('/content/drive/MyDrive/spam(1).csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [ ]:
df.shape

(5572, 3)

In [ ]:
import re

In [ ]:
def lower_cases(text):
 return text.lower()

def remove_char(text):
 pattern = r'[^a-zA-Z0-9\s]'
 text = re.sub(pattern, '', text)
 return text

In [ ]:
def remove_brackets(text):
 return re.sub('\[[^]]*\]', '', text)

In [ ]:
def remove_noise(text):
 text = remove_brackets(text)
 text = lower_cases(text)
 text = remove_char(text)
 return text

In [ ]:
df['Message'] = df['Message'].apply(remove_noise)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  go until jurong point crazy available only in ...     0
1      ham                            ok lar joking wif u oni     0
2     spam  free entry in 2 a wkly comp to win fa cup fina...     1
3      ham        u dun say so early hor u c already then say     0
4      ham  nah i dont think he goes to usf he lives aroun...     0

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
def stem_words(text):
 ps = PorterStemmer()
 stem_list = [ps.stem(word) for word in text.split()]
 text = ''.join(ps.stem(word) for word in text)

 return text

In [ ]:
df.head()

Category                                            Message  spam
0      ham  go until jurong point crazy available only in ...     0
1      ham                            ok lar joking wif u oni     0
2     spam  free entry in 2 a wkly comp to win fa cup fina...     1
3      ham        u dun say so early hor u c already then say     0
4      ham  nah i dont think he goes to usf he lives aroun...     0

In [ ]:
import nltk
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')
stoplis = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
def rm_stp_w(text):
  xtext = []
  for word in text.split():
    if word not in stoplis:
      xtext.append(word)

  final = xtext[:]
  xtext.clear()
  return final

In [ ]:
df['Message'] = df['Message'].apply(rm_stp_w)

In [ ]:
df['Message']

0       [go, jurong, point, crazy, available, bugis, n...
1                          [ok, lar, joking, wif, u, oni]
2       [free, entry, 2, wkly, comp, win, fa, cup, fin...
3           [u, dun, say, early, hor, u, c, already, say]
4       [nah, dont, think, goes, usf, lives, around, t...
                              ...                        
5567    [2nd, time, tried, 2, contact, u, u, 750, poun...
5568                      [b, going, esplanade, fr, home]
5569                     [pity, mood, soany, suggestions]
5570    [guy, bitching, acted, like, id, interested, b...
5571                                   [rofl, true, name]
Name: Message, Length: 5572, dtype: object

In [ ]:
def join_back(text):
  return ' '.join(text)

In [ ]:
df['Message'] = df['Message'].apply(join_back)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  go jurong point crazy available bugis n great ...     0
1      ham                            ok lar joking wif u oni     0
2     spam  free entry 2 wkly comp win fa cup final tkts 2...     1
3      ham                u dun say early hor u c already say     0
4      ham        nah dont think goes usf lives around though     0

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
X_train[:4]

3637    ME 2 BABE I FEEL THE SAME LETS JUST 4GET ABOUT...
3106                           Or remind me in a few hrs.
3722                Blank is Blank. But wat is blank? Lol
3889                   ok....take care.umma to you too...
Name: Message, dtype: object

In [ ]:
y_train[:4]

3637    0
3106    0
3722    0
3889    0
Name: spam, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x8348 sparse matrix of type '<class 'numpy.int64'>'
	with 38239 stored elements in Compressed Sparse Row format>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train_cv.shape

(4457, 7786)

In [ ]:
v.get_feature_names_out()[1771]

'cheer'

In [ ]:
v.vocabulary_

{'me': 4432,
 'babe': 1202,
 'feel': 2825,
 'the': 6847,
 'same': 5916,
 'lets': 4104,
 'just': 3899,
 '4get': 529,
 'about': 777,
 'it': 3780,
 'both': 1460,
 'try': 7091,
 'cheer': 1771,
 'up': 7223,
 'not': 4847,
 'fit': 2896,
 'soo': 6354,
 'muchxxlove': 4655,
 'locaxx': 4188,
 'or': 4988,
 'remind': 5717,
 'in': 3661,
 'few': 2841,
 'hrs': 3554,
 'blank': 1396,
 'is': 3768,
 'but': 1590,
 'wat': 7441,
 'lol': 4202,
 'ok': 4931,
 'take': 6719,
 'care': 1667,
 'umma': 7165,
 'to': 6963,
 'you': 7748,
 'too': 7002,
 'solve': 6328,
 'case': 1687,
 'man': 4359,
 'was': 7434,
 'found': 2986,
 'murdered': 4672,
 'on': 4949,
 'lt': 4268,
 'decimal': 2226,
 'gt': 3285,
 'afternoon': 875,
 'his': 3467,
 'wife': 7555,
 'called': 1628,
 'police': 5316,
 'questioned': 5558,
 'everyone': 2694,
 'sir': 6219,
 'sleeping': 6256,
 'when': 7525,
 'murder': 4671,
 'took': 7003,
 'place': 5251,
 'cook': 2013,
 'cooking': 2016,
 'gardener': 3101,
 'picking': 5225,
 'vegetables': 7307,
 'house': 3537,
 

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 529,  777, 1202, 1460, 1771, 2825, 2896, 3780, 3899, 4104, 4188,
        4432, 4655, 4847, 5916, 6354, 6847, 7091, 7223]),)

In [ ]:
X_train_np[0][1771]

1

In [ ]:
X_train_cv

<4457x7786 sparse matrix of type '<class 'numpy.int64'>'
	with 59637 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.95      0.92      0.94       149

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [ ]:
emails_count

<2x7786 sparse matrix of type '<class 'numpy.int64'>'
	with 22 stored elements in Compressed Sparse Row format>